export const studentProfile = {
  name: "Alex Johnson",
  id: "2021-CS-0042",
  program: "BS Computer Science",
  semester: "Fall 2026",
  gpa: 3.75,
  email: "alex.johnson@university.edu",
  phone: "+1 (555) 234-5678",
  dob: "March 15, 2003",
  address: "123 Campus Drive, Apt 4B, University City, CA 90210",
  advisor: "Dr. Sarah Williams",
  enrollmentDate: "September 1, 2021",
  avatar: null as string | null,
};

export const courses = [
  {
    id: "cs401",
    code: "CS-401",
    title: "Data Structures & Algorithms",
    instructor: "Prof. John Doe",
    credits: 3,
    progress: 72,
    grade: "A-",
    color: "#6c63ff",
    schedule: "Mon / Wed / Fri  9:00 AM",
    enrolled: true,
  },
  {
    id: "math202",
    code: "MATH-202",
    title: "Discrete Mathematics",
    instructor: "Dr. Emily Carter",
    credits: 3,
    progress: 60,
    grade: "B+",
    color: "#48c97e",
    schedule: "Tue / Thu  10:00 AM",
    enrolled: true,
  },
  {
    id: "eng101",
    code: "ENG-101",
    title: "Technical Writing",
    instructor: "Prof. Maria Garcia",
    credits: 2,
    progress: 80,
    grade: "A",
    color: "#f5a623",
    schedule: "Mon / Wed  1:00 PM",
    enrolled: true,
  },
  {
    id: "phy301",
    code: "PHY-301",
    title: "Physics for Engineers",
    instructor: "Dr. Alan Reed",
    credits: 3,
    progress: 55,
    grade: "B",
    color: "#e05c5c",
    schedule: "Tue / Thu  2:00 PM",
    enrolled: true,
  },
  {
    id: "cs305",
    code: "CS-305",
    title: "Operating Systems",
    instructor: "Prof. David Kim",
    credits: 3,
    progress: 65,
    grade: "A",
    color: "#29b6c8",
    schedule: "Mon / Wed / Fri  11:00 AM",
    enrolled: true,
  },
  {
    id: "cs410",
    code: "CS-410",
    title: "Computer Networks",
    instructor: "Dr. Nina Patel",
    credits: 3,
    progress: 40,
    grade: "B+",
    color: "#9b59b6",
    schedule: "Fri  2:00 PM",
    enrolled: true,
  },
];

export const navItems = [
  { id: "dashboard", label: "Dashboard",     icon: "home" },
  { id: "courses",   label: "My Courses",    icon: "book" },
  { id: "grades",    label: "Grades",        icon: "chart" },
  { id: "attendance",label: "Attendance",    icon: "calendar" },
  { id: "timetable", label: "Timetable",     icon: "clock" },
  { id: "messages",  label: "Messages",      icon: "mail" },
  { id: "settings",  label: "Settings",      icon: "settings" },
];
